// <auto-generated />
using System;
using AskiFatura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AskiFatura.Migrations
{
    [DbContext(typeof(AskiDbContext))]
    [Migration("20260908065257_IlkKurulum")]
    partial class IlkKurulum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AskiFatura.Models.Abone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TcKimlik")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Aboneler");
                });

            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AboneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KurulumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SayacSeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SayacTipi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AboneId");

                    b.ToTable("Sayaclar");
                });

            modelBuilder.Entity("AskiFatura.Models.Tahakkuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaturaDonemi")
                        .HasColumnType("text");

                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IlkOkumaDegeri")
                        .HasColumnType("numeric");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("SayacGorselYolu")
                        .HasColumnType("text");

                    b.Property<int>("SayacId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SonOkumaDegeri")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TuketimMiktari")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SayacId");

                    b.ToTable("Tahakkuklar");
                });

            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    b.HasOne("AskiFatura.Models.Abone", "Abone")
                        .WithMany("Sayaclar")
                        .HasForeignKey("AboneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abone");
                });

            modelBuilder.Entity("AskiFatura.Models.Tahakkuk", b =>
                {
                    b.HasOne("AskiFatura.Models.Sayac", "Sayac")
                        .WithMany("Tahakkuklar")
                        .HasForeignKey("SayacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sayac");
                });

            modelBuilder.Entity("AskiFatura.Models.Abone", b =>
                {
                    b.Navigation("Sayaclar");
                });

            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    b.Navigation("Tahakkuklar");
                });
#pragma warning restore 612, 618
        }
    }
}
