/* 
 * 1. OTOMATİK OLUŞTURULAN DOSYA UYARISI
 * <auto-generated />: Bu etiket, "Bu dosyayı sen elinle yazmadın, ben (EF Core) otomatik ürettim, 
 * o yüzden buraya girip manuel olarak kod ekleme/silme yapma, patlarız!" uyarısıdır.
 */
// <auto-generated />
using System;
using AskiFatura.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AskiFatura.Migrations
{
    /* 
     * 2. SNAPSHOT SINIFININ TANIMI
     * [DbContext(typeof(AskiDbContext))]: Bu fotoğrafın (snapshot), bizim 'AskiDbContext' 
     * isimli veritabanı köprümüze ait olduğunu sisteme bildirir.
     * ModelSnapshot sınıfından miras alarak, EF Core'un bu dosyayı referans noktası olarak kullanmasını sağlar.
     */
    [DbContext(typeof(AskiDbContext))]
    partial class AskiDbContextModelSnapshot : ModelSnapshot
    {
        /* 
         * 3. MODEL İNŞA METODU (FOTOĞRAFIN ÇİZİLDİĞİ YER)
         * BuildModel: Veritabanının o anki şemasını sıfırdan C# dilinde tarif eden ana metottur.
         */
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            /* 
             * 4. GENEL VERİTABANI AYARLARI
             * ProductVersion: Bu snapshot'ın EF Core'un hangi sürümüyle (10.0.11) oluşturulduğunu tutar.
             * MaxIdentifierLength(63): PostgreSQL'de tablo veya kolon isimlerinin maksimum 63 karakter 
             * olabileceğini belirten, Npgsql'e (Postgres eklentisine) ait bir kısıtlamadır.
             * UseIdentityByDefaultColumns: PostgreSQL'deki tüm ID'lerin varsayılan olarak "Otomatik Artan" 
             * (Identity) olacağını genel bir kural olarak sisteme işler.
             */
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            /* 
             * 5. ABONELER TABLOSUNUN HEYKELİ (ENTITY)
             * modelBuilder.Entity("AskiFatura.Models.Abone", ...): "Abone şablonumun veritabanındaki 
             * izdüşümü tam olarak şöyledir:" diyerek başlar.
             */
            modelBuilder.Entity("AskiFatura.Models.Abone", b =>
                {
                    /* ID Kolonu: Otomatik artan (ValueGeneratedOnAdd) bir tam sayı. */
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    /* Ad Kolonu: Zorunlu (IsRequired), maks 50 karakter ve VARCHAR(50) tipinde. */
                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    /* Adres Kolonu: Sınır yok, düz 'text' tipinde. */
                    b.Property<string>("Adres")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    /* TC Kimlik Kolonu: Zorunlu, tam 11 karakter VARCHAR(11). */
                    b.Property<string>("TcKimlik")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    /* HasKey: Bu tablonun kilidi (Primary Key) "Id" kolonudur. */
                    b.HasKey("Id");

                    /* ToTable: Tüm bu yapıyı PostgreSQL'de "Aboneler" ismiyle haritala. */
                    b.ToTable("Aboneler");
                });

            /* 
             * 6. SAYAÇLAR TABLOSUNUN HEYKELİ
             */
            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    /* AboneId: Yabancı anahtarımız (Foreign Key) burada fiziksel bir sayısal kolon olarak tutuluyor. */
                    b.Property<int>("AboneId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KurulumTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SayacSeriNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SayacTipi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    /* HasIndex: Performans için AboneId kolonuna indeks (fihrist) atılmış durumda. */
                    b.HasIndex("AboneId");

                    b.ToTable("Sayaclar");
                });

            /* 
             * 7. TAHAKKUKLAR TABLOSUNUN HEYKELİ
             */
            modelBuilder.Entity("AskiFatura.Models.Tahakkuk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FaturaDonemi")
                        .HasColumnType("text");

                    /* Parasal ve metreküp (m3) değerleri 'numeric' (decimal) tipinde güvence altına alınıyor. */
                    b.Property<decimal>("FaturaTutari")
                        .HasColumnType("numeric");

                    b.Property<decimal>("IlkOkumaDegeri")
                        .HasColumnType("numeric");

                    b.Property<bool>("OdendiMi")
                        .HasColumnType("boolean");

                    b.Property<string>("SayacGorselYolu")
                        .HasColumnType("text");

                    b.Property<int>("SayacId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SonOdemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("SonOkumaDegeri")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TuketimMiktari")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("SayacId");

                    b.ToTable("Tahakkuklar");
                });

            /* 
             * 8. İLİŞKİLERİN (RELATIONSHIPS) KURULMASI - EN ÖNEMLİ KISIM!
             * Buraya kadar tabloları tek tek tanıttı. Şimdi tabloların birbirine nasıl bağlandığını (JOIN kurallarını) tanımlıyor.
             */
            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    /* 
                     * HasOne & WithMany: "Her Sayacın BİR (HasOne) Abonesi vardır. 
                     * O Abonenin de BİRDEN FAZLA (WithMany) Sayacı olabilir."
                     * HasForeignKey: Bu bağlantı 'AboneId' kolonu üzerinden yapılır.
                     * OnDelete(Cascade): Abone silinirse, sayaçları da acımasızca (Cascade) silinir.
                     */
                    b.HasOne("AskiFatura.Models.Abone", "Abone")
                        .WithMany("Sayaclar")
                        .HasForeignKey("AboneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    /* C# tarafında 'Sayac.Abone' diyerek üst nesneye ulaşabilmemizi onaylıyor. */
                    b.Navigation("Abone");
                });

            modelBuilder.Entity("AskiFatura.Models.Tahakkuk", b =>
                {
                    /* Aynı şekilde: "Her Faturanın BİR Sayacı, Her Sayacın BİRDEN FAZLA Faturası (Tahakkuku) vardır." */
                    b.HasOne("AskiFatura.Models.Sayac", "Sayac")
                        .WithMany("Tahakkuklar")
                        .HasForeignKey("SayacId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sayac");
                });

            /* 
             * 9. LİSTE (KOLEKSİYON) YÖNLENDİRMELERİ
             * Yukarıda Abone'den Sayac'a gidişi tanımlamıştık. 
             * Burada ise tam tersi; Abone sınıfının içindeki 'Sayaclar' listesinin ve 
             * Sayac sınıfının içindeki 'Tahakkuklar' listesinin aktif olduğunu onaylıyor.
             */
            modelBuilder.Entity("AskiFatura.Models.Abone", b =>
                {
                    b.Navigation("Sayaclar");
                });

            modelBuilder.Entity("AskiFatura.Models.Sayac", b =>
                {
                    b.Navigation("Tahakkuklar");
                });
#pragma warning restore 612, 618
        }
    }
}